CREATE TABLE IF NOT EXISTS atomic_ingredients (
  id BIGSERIAL PRIMARY KEY,
  ri_id BIGINT NOT NULL UNIQUE,

  ri_name VARCHAR(100) NOT NULL,
  qty DECIMAL(9,2) DEFAULT NULL,    
  units VARCHAR(10) DEFAULT NULL,
  servings DECIMAL(9,2) DEFAULT NULL,
  density DECIMAL(9,2) DEFAULT NULL,
  serving_size DECIMAL(9,2) DEFAULT NULL,
  atomic BOOLEAN DEFAULT TRUE,

  allergens       VARCHAR(150) ARRAY,
  tags            VARCHAR(150) ARRAY,
  user_tags       VARCHAR(150) ARRAY,  
  
  image_file VARCHAR(100) DEFAULT NULL,
  text_file VARCHAR(100) DEFAULT NULL,
  ri_desc VARCHAR(500) DEFAULT NULL,
  external_data_ref VARCHAR(150) ARRAY,
  
  n_En DECIMAL(9,2) DEFAULT NULL,
  n_Fa DECIMAL(9,2) DEFAULT NULL,
  n_Fs DECIMAL(9,2) DEFAULT NULL,
  n_Fm DECIMAL(9,2) DEFAULT NULL,
  n_Fp DECIMAL(9,2) DEFAULT NULL,
  n_Fo3 DECIMAL(9,2) DEFAULT NULL,
  n_Ca DECIMAL(9,2) DEFAULT NULL,
  n_Su DECIMAL(9,2) DEFAULT NULL,
  n_Fb DECIMAL(9,2) DEFAULT NULL,
  n_St DECIMAL(9,2) DEFAULT NULL,
  n_Pr DECIMAL(9,2) DEFAULT NULL,
  n_Sa DECIMAL(9,2) DEFAULT NULL,
  n_Al DECIMAL(9,2) DEFAULT NULL
);