CREATE TABLE IF NOT EXISTS exploded (
  id BIGSERIAL PRIMARY KEY,
  ri_id BIGINT NOT NULL UNIQUE,

  ri_name VARCHAR(100) NOT NULL,
  igdt_type SMALLINT DEFAULT -1,
  
  ingredients     VARCHAR(1000) ARRAY
);