CREATE TABLE IF NOT EXISTS tag_sets (
  uuid_user VARCHAR(100) NOT NULL UNIQUE PRIMARY KEY,
  allergens VARCHAR(50) ARRAY,
  ingredient_exc VARCHAR(50) ARRAY,
  tags VARCHAR(50) ARRAY,
  types VARCHAR(50) ARRAY
);