FROM postgres:13

EXPOSE 5432

ENV POSTGRES_USER simon
ENV POSTGRES_PASSWORD pool

CMD ["postgres"]


# build with
# cd /Users/simon/a_syllabus/lang/python/mysql_python/docker_postgres		# CHECK PROCESS
# docker build -t postgres-rcp:13-custom .

# run with
# docker run -p 5432:5432 postgres-rcp:13-custom